### ISSUE TITLE
Followup :  "Crash on load after last update"

### ISSUE THREAD

**Issue by ianjirka** [tburrows13/PowerOverload#1]
Re: this thread https://mods.factorio.com/mod/PowerOverload/discussion/628e971fcdceb5ddc5f83fd6

I'm able to reproduce this by only moving fuses.lua from data to data-updates. 

    14.203 Error ModManager.cpp:1588: Failed to load mod "PowerOverload": PowerOverload/prototypes/fuse-recipes.lua:20: bad argument #1 of 2 to 'pairs' (table expected, got nil)
    stack traceback:
    [C]: in function 'pairs'
    PowerOverload/prototypes/fuse-recipes.lua:20: in main chunk
    [C]: in function 'require'
    PowerOverload/data-updates.lua:2: in main chunk

Attached is a save file you can sync mods and settings to.  You'll need to enable PowerOverload after.

[repro.zip](https://github.com/tburrows13/PowerOverload/files/8781911/repro.zip)

**Comment by tburrows13** [comment]
This was fixed in 1.2.4.
